NODE_FILE		        C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/network/Node.txt
LINK_FILE		        C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/network/link.txt
LOCATION_FILE		    C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/network/Location.txt
CONNECTION_FILE	    	C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/network/Connection.txt
PARKING_FILE	    	C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/network/Parking.txt
ZONE_FILE		        C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/network/Zone.txt
SIGN_FILE		        C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/network/Sign.txt
SIGNAL_FILE		        C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/network/Signal.txt
TIMING_PLAN_FILE    	C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/network/timing_plan.txt
PHASING_PLAN_FILE   	C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/network/phasing_plan.txt
DETECTOR_FILE		    C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/network/detector.txt
TRIP_FILE		        C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/demand/trip.txt
VEHICLE_TYPE_FILE   	C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/demand/Vehicle_Type.txt
VEHICLE_FILE		    C:/Users/vsokolov/usr/polaris/TransimsData/TestNet50/demand/vehicle.txt
NEW_SQLITE_DATABASE     C:/Users/vsokolov/usr/polaris_io/Transims2Polaris/TestNet50.sqlite