#######NETWORK##############
NODE_FILE		        C:/Users/vsokolov/usr/transims/Run4_1/network/Node
LINK_FILE		        C:/Users/vsokolov/usr/transims/Run4_1/network/Link
LOCATION_FILE		    C:/Users/vsokolov/usr/transims/Run4_1/network/Location
CONNECTION_FILE	    	C:/Users/vsokolov/usr/transims/Run4_1/network/Connection
PARKING_FILE	    	C:/Users/vsokolov/usr/transims/Run4_1/network/Parking
ZONE_FILE		        C:/Users/vsokolov/usr/transims/Run4_1/network/Zone
POCKET_FILE		        C:/Users/vsokolov/usr/transims/Run4_1/network/Pocket
SHAPE_FILE		        C:/Users/vsokolov/usr/transims/Run4_1/network/Shape

#######DEMAND##############
#TRIP_FILE		        C:/Users/vsokolov/usr/transims/Run4_1/demand/regional_trips
#VEHICLE_TYPE_FILE   	C:/Users/vsokolov/usr/transims/Run4_1/inputs/vehicle_type_V5
#VEHICLE_FILE		    C:/Users/vsokolov/usr/transims/Run4_1/demand/regional_vehicle



#######CONTROL##############
#SIGN_FILE		        C:/Users/vsokolov/usr/transims/Run4_1/intcontrol/Sign
#SIGNAL_FILE		        C:/Users/vsokolov/usr/transims/Run4_1/intcontrol/Signal
#TIMING_PLAN_FILE    	C:/Users/vsokolov/usr/transims/Run4_1/intcontrol/timing_plan
#PHASING_PLAN_FILE   	C:/Users/vsokolov/usr/transims/Run4_1/intcontrol/phasing_plan

#######OUTPUT##############
NEW_SQLITE_DATABASE     C:/Users/vsokolov/usr/polaris_io/Transims2Polaris/chicago
#NEW_SQLITE_DATABASE     C:/Users/vsokolov/usr/polaris_io/Transims2Polaris/chicago_with_demand.sqlite


#######MISC##############
#GENERATE_TRIP_WITH_REF 	FALSE
MESSAGE 					The sign, signal, timing and phasing files were generated by IntControl
ADD_GEOMETRY				FALSE
SRID						26916
